### ISSUE TITLE
Changing dynamically the color when moving.

### ISSUE THREAD

**Issue by pedefe** [yoannmoinet/nipplejs#28]
I wish to change dynamically the color of joystick from "gray" when iddle to other color when moving, and back to "gray" on "end" event.
How to do that ?
I have tried to change niddle.options.color in "move" function processing, but nothing occurs
Best regards.

**Comment by yoannmoinet** [comment]
You should be able to do it via CSS and classes :

Javascript : 
```javascript
var manager = nipplejs.create();
manager.on('added', function (nipple) {
    nipple.on('start', function () {
        nipple.el.classList.add('active');
    }).on('end', function () {
        nipple.el.classList.remove('active');
    });
});
```

CSS : 
```css
.nipple div {
    background-color: white;
}

.nipple.active div {
    background-color: red;
}
```

I didn't test it though, so keep me posted if it doesn't work.
Note that `classList` is not available in IE9-.
